<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Parent_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get parent by user_id
     */
    function get_parent($user_id)
    {
        return $this->db->get_where('parents',array('user_id'=>$user_id))->row_array();
    }
        
    /*
     * Get all parents
     */
    function get_all_parents()
    {
        $this->db->order_by('user_id', 'desc');
        return $this->db->get('parents')->result_array();
    }
        
    /*
     * function to add new parent
     */
    function add_parent($params)
    {
        $this->db->insert('parents',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update parent
     */
    function update_parent($user_id,$params)
    {
        $this->db->where('user_id',$user_id);
        return $this->db->update('parents',$params);
    }
    
    /*
     * function to delete parent
     */
    function delete_parent($user_id)
    {
        return $this->db->delete('parents',array('user_id'=>$user_id));
    }
}
