<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Teacher_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->db->cache_on();
    }
    
    /*
     * Get teacher by userid
     */
    function get_teacher($userid)
    {
        return $this->db->get_where('teachers',array('userid'=>$userid))->row_array();
    }
        
    /*
     * Get all teachers
     */
    function get_all_teachers()
    {
        $this->db->select('*');
        $this->db->from('teachers');
        $this->db->join('users', 'users.id = teachers.id');
        return $this->db->get()->result_array();
        
    }
        
    /*
     * function to add new teacher
     */
    function add_teacher($params)
    {
        $this->db->insert('teachers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update teacher
     */
    function update_teacher($userid,$params)
    {
        $this->db->where('userid',$userid);
        return $this->db->update('teachers',$params);
    }
    
    /*
     * function to delete teacher
     */
    function delete_teacher($userid)
    {
        return $this->db->delete('teachers',array('userid'=>$userid));
    }
}
