<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Parent_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->db->cache_on();
    }
    

    function get_parent($user_id)
    {
        return $this->db->get_where('parents',array('user_id'=>$user_id))->row_array();
    }
        

    function get_all_parents()
    {
        $this->db->select('*');
        $this->db->from('parents');
        $this->db->join('users', 'parents.user_id = users.id');
        return $this->db->get()->result_array();

    }
        
    /*
     * function to add new parent
     */
    function add_parent($params)
    {
        $this->db->insert('parents',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update parent
     */
    function update_parent($user_id,$params)
    {
        $this->db->where('user_id',$user_id);
        return $this->db->update('parents',$params);
    }
    
    /*
     * function to delete parent
     */
    function delete_parent($user_id)
    {
        return $this->db->delete('parents',array('user_id'=>$user_id));
    }
}
